### ISSUE TITLE
Prepare for 1.0.0 release

### ISSUE THREAD

**Issue by yurrriq** [lfe-mug/elli_lmug#2]
- [x] Add docstring to [`handle/2`](http://lfe-mug.github.io/lmug-elli/lmug-elli.html#func-handle.2F2)
- [ ] Handle `(request-ssl-client-cert)` in [`handle/2`](http://lfe-mug.github.io/lmug-elli/lmug-elli.html#func-handle.2F2)
- [x] ~~Add docstring to `handle/3`~~
- [x] ~~Add docstring to `(elli)->port-name` `convert-port-name`~~
- [x] ~~Add docstring to `(elli)->scheme` `convert-scheme`~~
- [x] ~~Add docstring to `(elli)->protocol` `convert-protocol`~~
- [x] ~~Add docstring to `(elli)->method` `convert-method`~~
- [x] Add module-level docstring to `lmug-elli`
- [ ] Write more tests: TBD
- [ ] Flesh out documentation/examples: TBD
- [x] Add docstring to [`run/2`](http://lfe-mug.github.io/lmug-elli/lmug-elli.html#func-run.2F2)

**Comment by oubiwann** [comment]
lmug has gotten a massive rewrite and is much, much simpler. I'm closing many old tickets and creating new ones for next steps.
