### ISSUE TITLE
Use all appropriate lmug-util functions

### ISSUE THREAD

**Issue by yurrriq** [lfe-mug/elli_lmug#6]
- [x] `normalize-http-verb/1` (#5)
- [ ] `split-query/1` (pending lfe-mug/lmug#33)
- [ ] `get-host-data` and/or `split-host-data`
  - Make sure these functions handle https correctly.

**Comment by oubiwann** [comment]
lmug has gotten a massive rewrite and is much, much simpler. I'm closing many old tickets and creating new ones for next steps.
