### ISSUE TITLE
Discuss how (whether?) to handle {pre,post}process

### ISSUE THREAD

**Issue by yurrriq** [lfe-mug/elli_lmug#8]
I'm not sure how exactly they should fit in with lmug, or if they should at all. Are there generic analogs across different webservers?

**Comment by yurrriq** [comment]
Bump.

This is the main issue holding me back from dogfooding `lmug-elli` at work.

**Comment by yurrriq** [comment]
On second thought we can probably handle pre- and post-processing just fine via normal Ring strategies. The real key difference from other webservers, perhaps, is that elli handlers can throw a response (or error to become a 500) at any time, thus short-circuiting the flow. While we can handle that easily in elli-lmug, being aware of the behaviour, I wonder how that might translate across other web servers generically.

If I write an lmug handler that throws to short circuit, how should I expect it to behave when I swap yaws for elli, for example?

**Comment by oubiwann** [comment]
lmug has gotten a massive rewrite and is much, much simpler. I'm closing many old tickets and creating new ones for next steps.
